### ISSUE TITLE
Let's try 300 tiles per page

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#113]
Clicking the next button is quite slow. Could you please create a branch where you limit each page to 300 instead of 27. I'm curious how fast it loads on mobile and what you recommend.

**Comment by rodmeurer** [comment]
@dankohn you mean at the Speaker's Bureau right? We only have 94 speakers (after disabling gravatar) wich we can divide in 45 tiles per page to test the pagination, is it ok?.

**Comment by dankohn** [comment]
I'm suggesting that having all of them on one page would be better.

**Comment by rodmeurer** [comment]
Ok, We'll work on this.

**Comment by rodmeurer** [comment]
@dankohn displaying all in one page https://fz-113-cncf.pantheonsite.io/speakers/

**Comment by dankohn** [comment]
It loads fine for me on desktop and mobile? @cjyabraham WDYT?

**Comment by rodmeurer** [comment]
Right @dankohn,  just see it also. We'll fix that.

**Comment by cjyabraham** [comment]
I think the downside is that it takes longer to load.  I did a [quick test](https://docs.google.com/spreadsheets/d/1BjVl_x5MwwrbrDHEdNr9RAyeNbVMn7iZRzykZ_8MTrA/edit?usp=sharing) and found the load time to be about twice as long for 245 instead of 27, and that's with many of the speakers having just the default photo.  If all 245 had real photos then it would take quite a bit longer.

In the future we could implement some kind of lazyloading but, until then, my vote is to stay with the paginated version for now.

**Comment by dankohn** [comment]
Then what could we reasonably increase to? 100 per page?
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
I just [tested 103](https://docs.google.com/spreadsheets/d/1BjVl_x5MwwrbrDHEdNr9RAyeNbVMn7iZRzykZ_8MTrA/edit#gid=0) and it takes about 60% longer to load than for 27.  I guess that's ok.  Or we could go with a few less, say, 81 (which is a multiple of 3)?

**Comment by dankohn** [comment]
Let's do 81.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by rodmeurer** [comment]
@cjyabraham set to 81 tiles per page.

**Comment by cjyabraham** [comment]
deployed
