### ISSUE TITLE
New FAQ design

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#121]
I'm going to be replacing the text on https://www.cncf.io/about/faq/ and want a new design. The key functionality I'm looking for is that all the sections are always showing but that clicking on a header (which will be a question) changes the URL to https://www.cncf.io/about/faq/ #security-question so that I can link directly to answers.

We came up with a very sophisticated design for the new events site:

https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/program/super-long-multi-part-page/#cloud-native-transformation-summit

This is a simpler implementation:

https://kubernetescommunitydays.org/organizing/#logos-and-trademarks

@cjyabraham Any suggestions?

**Comment by deigolocco** [comment]
I'll take at look @cjyabraham

**Comment by pablodelarocha** [comment]
@dankohn and @cjyabraham heres a design suggestion according to your request. Please let us know if this is ok - i already discussed about this with @deigolocco and he said it can be done 
![FAQ](https://user-images.githubusercontent.com/54405572/66609228-df8db400-eb8e-11e9-8e2f-41b80e99d99a.jpg)

**Comment by cjyabraham** [comment]
A few comments:
- I don't think you need the "Copylink" icon to pop up.  When you scroll down the page to the various section the url should automatically update with the hash.  See [how we do it here](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/call-for-proposals/#suggested-topics).
- I don't like the ">" icons to the left of each of the menu items.  To me, they make it look like the menu item will expand in place.  Maybe try and different icon or no icon at all?

**Comment by pablodelarocha** [comment]
@cjyabraham yeah, i guess it works without the ">". Let us know if this is ok now.
![FAQ](https://user-images.githubusercontent.com/54405572/66650406-ec4dee80-ec06-11e9-907a-95732b71a584.jpg)

**Comment by cjyabraham** [comment]
LGTM.  @dankohn @KimMcMahon ?

**Comment by deigolocco** [comment]
guys the page is done https://fz-121-cncf.pantheonsite.io/about/faq/

No deploy is necessary, because we did everything through manager.

But differently of the [reference page](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/program/super-long-multi-part-page/#cloud-native-transformation-summit), we don't have sections under the FAQ, so using the side navigation we can't have last items scrolled to the top.
<img width="1469" alt="Captura de Tela 2019-10-15 às 18 31 27" src="https://user-images.githubusercontent.com/5631313/66872086-800f1a00-ef7b-11e9-9e69-800efe389141.png">

I don't think this is a problem, but the options that we have to "fix" is add a new section under or a empty space.

**Comment by dankohn** [comment]
Could you please figure out an approach for mobile. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by pablodelarocha** [comment]
Sure @dankohn ! Does the below design for mobile works?
![FAQ_mobile](https://user-images.githubusercontent.com/54405572/66948462-236b3800-f02b-11e9-90a8-205e8e11b295.jpg)

**Comment by dankohn** [comment]
Does selecting from the dropdown change the fragment ID in the URL and automatically jump you to the right section? If so, than LGTM

**Comment by deigolocco** [comment]
yes @dankohn, thanks! We'll proceed here

**Comment by cjyabraham** [comment]
there's a problem when you scroll to the bottom of the page:
<img width="781" alt="Screen Shot 2019-10-17 at 2 51 05 PM" src="https://user-images.githubusercontent.com/463160/66988947-9d63f580-f0ed-11e9-9513-4195bc7a019a.png">
Note how it is done on the [reference site](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/program/super-long-multi-part-page/).

**Comment by deigolocco** [comment]
fixed and adjusted to work on mobile
https://fz-121-cncf.pantheonsite.io/about/faq/

**Comment by cjyabraham** [comment]
A couple of issues:
- when I click on the last entry in desktop view it doesn't highlight in the left column but instead highlights the second-to-last entry
- in mobile, the question picker looks like a drop-down but behaves like an accordion: when you click it open, the questions show up below it rather than inside the drop-down.  First, do we need to have this expandable at all or can we just show all questions on page load on mobile like we do [on the events site](https://events.linuxfoundation.org/agl-amm/program/cfp/)? @dankohn ?

**Comment by dankohn** [comment]
We want to show all questions on mobile, please.

**Comment by deigolocco** [comment]
ok guys, we're adjusting the mobile to let them open.

@cjyabraham as I mentioned on my [first interaction](https://github.com/cncf/wordpress-site/issues/121#issuecomment-542418075) we don't have space under the FAQ section to scroll until the last item.
I did a simulation how much space do we need for that
<img width="1678" alt="Captura de Tela 2019-10-28 às 09 28 17" src="https://user-images.githubusercontent.com/5631313/67678615-d316a300-f965-11e9-96e0-d3db63d1aebf.png">

Or we can add another section under as we did for webinars
<img width="1678" alt="Captura de Tela 2019-10-28 às 09 28 08" src="https://user-images.githubusercontent.com/5631313/67678669-fc373380-f965-11e9-8a09-538078eced2d.png">

Please let us know what you prefer.

**Comment by cjyabraham** [comment]
@deigolocco I think you misunderstand my statement.  When I click on the last link in the menu it doesn't highlight.  Can you get it to highlight?  I understand that you can't scroll that content to the top of the window.  That's not a problem for me.

Here is the screen right after I click on the last menu item.  You see, the second-to-last item is highlighted and not the last:

<img width="708" alt="Screen Shot 2019-10-28 at 11 26 52 PM" src="https://user-images.githubusercontent.com/463160/67697034-7bfee580-f9da-11e9-9a9a-3b164f8eda8c.png">

Mobile menu looks good but could you remove some of the whitespace at the top before the menu and make the menu a bit more compact:

<img width="311" alt="Screen Shot 2019-10-28 at 11 28 23 PM" src="https://user-images.githubusercontent.com/463160/67697196-c1bbae00-f9da-11e9-94cd-8ecb68311e51.png">

**Comment by deigolocco** [comment]
@cjyabraham we're still working. 
About you question is not possible, the item needs to be at the top of the page, so without an extra space below this is not be possible. We can force on click, but I believe this will be a "false positive" and may confuse the user, because he/she will see a different item at the top compared to the highlight menu item.

**Comment by deigolocco** [comment]
@cjyabraham the adjustments for mobile are done, please confirm if we need to force the active statement onclick at menu.

**Comment by cjyabraham** [comment]
LGTM.  @dankohn, ok to deploy?

@deigolocco I assume that I'll deploy the code then you'll go in and apply the template in the wp-admin?

**Comment by dankohn** [comment]
Yes, please deploy. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by cjyabraham** [comment]
@deigolocco can you resolve merge conflicts please and then I'll deploy?

**Comment by deigolocco** [comment]
fixed @cjyabraham.
After the deploy I'll apply the template.

**Comment by cjyabraham** [comment]
Ok deployed.
@deigolocco can you apply the template?

**Comment by deigolocco** [comment]
applied @cjyabraham

**Comment by cjyabraham** [comment]
Looks great!

**Comment by deigolocco** [comment]
@cjyabraham we did an adjustment, when a user is logged in
![image](https://user-images.githubusercontent.com/5631313/67997606-9384db00-fc33-11e9-8906-cd84d92577e2.png)
It's fixed, could you deploy one more time please?

**Comment by cjyabraham** [comment]
Ok.  Deployed.
