### ISSUE TITLE
Can't update emails in ultimate member

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#150]
When you try and edit the body of [the emails](https://www.cncf.io/wp-admin/admin.php?page=um_options&tab=email) and click "save" the changes don't stick.

**Comment by deigolocco** [comment]
@cjyabraham we did some tests and this is a writing permission issue.
When we edit a email template, the file is saved at `themes/salient-child/ultimate-member/email`
However at homologation and production envs the application doesn't have permission to create files, so we can't save.
We tried to create manually by FTP without success.
Someone with server access could chance the permissions? This will solve the issue.

**Comment by cjyabraham** [comment]
Ok.  Thanks.  Looks like I can edit locally and create files in salient-child and then commit them to the repo to get deployed live.

**Comment by deigolocco** [comment]
Locally it works, but this shouldn't be versionated. This template must be dynamic because at manager when you save a template the file is create/update, and this is not working without change the folder permissions.
![Captura de tela de 2019-11-29 10-40-50](https://user-images.githubusercontent.com/5631313/70140926-9cbef880-1674-11ea-98a8-7d4b66e40297.png)
Did you change the folder permission?

**Comment by cjyabraham** [comment]
As discussed, please check if the emails work in the same way in the new version of UM plugin.

**Comment by deigolocco** [comment]
@cjyabraham exactly the same

**Comment by cjyabraham** [comment]
thanks for checking
