### ISSUE TITLE
CNCF Staff Page

### ISSUE THREAD

**Issue by taylorwaggoner** [cncf/wordpress-site#164]
When adding new staff members to https://www.cncf.io/people/staff/, we change the "publish" date and time in order to keep Dan and Chris as the first and second entries on the page (meaning everyone after Dan and Chris is organized alphabetically with a later and later publish time).  Is there any plan to change this in the website rebuild?  Would it be possible to have them as entries that we can "reorder" instead, to keep Dan and Chris at the top?

![image](https://user-images.githubusercontent.com/34756611/73690486-53475580-4685-11ea-8bd8-188fe4ad2a16.png)

**Comment by cjyabraham** [comment]
Hi @taylorwaggoner , yes, [we have this down as a key requirement](https://docs.google.com/document/d/1rsgfAKWY0MC70ddX0a0eYV91VenG_loT_tS8aoGz0cQ/edit#heading=h.9w82y1yfck2) for the new CNCF site and will make sure we build something that makes this a lot easier to manage.  I'll close this issue for now since we won't be using this repo anymore.
