### ISSUE TITLE
CNCF Rebuild

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#4]
This is a long term project to completely rewrite the CNCF site to achieve the following:
- faster load times
- faster admin UI
- easier administration leveraging Gutenberg
- easier development process through use of CI, github, etc.
- streamlined and enhanced features
- automated testing to catch render errors prior to deployment; visual regression tests using wraith 

The project will adopt a similar infrastructure and core template to what is used on the [LFEvents Rebuild project](https://github.com/LF-Engineering/lfevents).

**Comment by cjyabraham** [comment]
Request from @taylorwaggoner: turn projects listed on [project pages](https://www.cncf.io/sandbox-projects/) into a CPT so that they can be more easily configured

**Comment by cjyabraham** [comment]
@KimMcMahon asks that all the projects are kept in the DB once so that all filters and such can easily be updated across the site when a project changes category or if there's a new project added etc.

**Comment by taylorwaggoner** [comment]
@cjyabraham wanted to check on timeline for this issue.  I had an example pop up today about why the project pages need to be updated: CloudEvents is moving from Sandbox to Incubating - in order to make this change in WordPress, I have to manually copy and paste all of CloudEvent's info from the edit screen of https://www.cncf.io/sandbox-projects/ to the edit screen of https://www.cncf.io/projects/.  It would be a much better experience if all I need to do was select the project level from a dropdown on a CloudEvents project page, or similar.  Thanks!

**Comment by cjyabraham** [comment]
Sounds good @taylorwaggoner .  We should be kicking of development of the rebuild in the next month or two.

**Comment by cjyabraham** [comment]
closing this in favor of [this board](https://github.com/cncf/cncf.io/projects/1?fullscreen=true).
