### ISSUE TITLE
Reduce image sizes on case studies page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#89]
A lot of the [image sizes on this page](https://www.cncf.io/projects/case-studies/) can be reduced significantly.  The [spotify one](https://www.cncf.io/wp-content/uploads/2019/06/CaseStudy_spotify_banner4.jpg), for example, is 450K.  It could be cropped and shrunk.

Can you also go through all the individual case studies and shrink the images there too.  For example, [on this page](https://www.cncf.io/case-study/adform/), [this image](https://www.cncf.io/wp-content/uploads/2019/08/adform-3.jpg) is 455K because its actual width is 1500px though it only needs to be 400px. 

After this is done, @alexcontini, can you also make an effort to keep these small going forward?  I know you, Chris B and I discussed this already but is there anyone else that we need to discuss this with?

**Comment by alexcontini** [comment]
@cjyabraham  sounds good!

I have gone through some already and replaced all the images with smaller ones - all are now about 50kb - 150kb (Apester, Ant Financial, Spotify, Box, Appdirect) - the only one that was looking a bit blurry when I reduced it a lot was the top banner image so I kept those about 1000px wide

For the featured images, I have replaced those for the ones I have done already, but I realized that I should probably wait until the automatic overlay feature is added - because right now I am adding the color overlay manually so those will have to be replaced again once the feature is added (all images will have to be black and white when it is)

So I think I will go though and replace images on the individual case studies for now, and then once the overlay feature is added, I will replace all featured images

**Comment by cjyabraham** [comment]
Ok.  Thanks.  
Just an FYI that we may not add the overlay feature until we rebuild the CNCF site.

**Comment by cjyabraham** [comment]
@alexcontini can you look at the images on [this page too](https://www.cncf.io/community/kubecon-cloudnativecon-events/).  Several of the background images there too could be reduced by a huge amount.

**Comment by cjyabraham** [comment]
Any updates on this @alexcontini?

**Comment by alexcontini** [comment]
@cjyabraham sorry about the delay with this, I have updated the images and https://www.cncf.io/projects/case-studies/ and https://www.cncf.io/community/kubecon-cloudnativecon-events/ are all now 150kb or smaller. 

I also went through the individual ones and reduced the sizes and have worked with Julie to make them smaller going forward. For the top banner, I tried making them a lot smaller and they appear blurry so I think they need to be about 1000px or wider to look high res

**Comment by cjyabraham** [comment]
Thanks for doing this.

The page that doesn't look done, however, is [this page](https://www.cncf.io/projects/case-studies/). I'm still seeing quite a few over 150k.  And wouldn't it be better to use jpegs instead of pngs for these?  I think this can be lower priority now but it'd be good to get this done when you have time.

<img width="715" alt="Screen Shot 2019-10-02 at 12 17 59 PM" src="https://user-images.githubusercontent.com/463160/66019742-c346a300-e50e-11e9-99c7-c66d5140a13a.png">

**Comment by cjyabraham** [comment]
We can close this for now since we'll do it a different way on the new site.
